Load packages

In [2]:
!pip install pandas

WARNING: Skipping /opt/conda/lib/python3.11/site-packages/nlopt-2.7.1.dist-info due to invalid metadata entry 'name'
Collecting pandas
  Downloading pandas-3.0.1-cp311-cp311-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (79 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 79.5/79.5 kB 3.2 MB/s eta 0:00:00
Requirement already satisfied: numpy>=1.26.0 in /opt/conda/lib/python3.11/site-packages (from pandas) (2.0.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/conda/lib/python3.11/site-packages (from pandas) (2.9.0)
Requirement already satisfied: six>=1.5 in /opt/conda/lib/python3.11/site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Downloading pandas-3.0.1-cp311-cp311-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (11.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.3/11.3 MB 45.4 MB/s eta 0:00:00:00:0100:01
WARNING: Skipping /opt/conda/lib/python3.11/site-packages/nlopt-2.7.1.dist-info due to invalid metadata entry 'name'
Installing collected packages: pandas
Successfully installed pandas-3.0.1

In [11]:
!pip install openpyxl

WARNING: Skipping /opt/conda/lib/python3.11/site-packages/nlopt-2.7.1.dist-info due to invalid metadata entry 'name'
Collecting openpyxl
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 250.9/250.9 kB 13.6 MB/s eta 0:00:00
Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
WARNING: Skipping /opt/conda/lib/python3.11/site-packages/nlopt-2.7.1.dist-info due to invalid metadata entry 'name'
Installing collected packages: et-xmlfile, openpyxl
Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5

In [12]:
import pandas as pd

Load datasets & Preview

1. Merchandise Sales

In [15]:
merchandise_sales_df = pd.read_excel("FirstByte/merchandise_sales.xlsx")
merchandise_sales_df.head()

,Product_ID,Barcode,Item_Category,Item_Name,Size,Unit_Price,Customer_Age_Group,Customer_Region,Promotion,Channel,Selling_Date,Member_ID,Arrival_Date
0,10000000,20000000,Cap,Classic Cap,NaN,35,18–25,Domestic,False,Online,2024-02-14 09:30:00,10008632,2024-02-22 13:49:00
1,10000000,20000001,Cap,Classic Cap,NaN,35,26–40,Domestic,False,Team Store,2024-01-31 14:30:00,10005467,NaT
2,10000000,20000002,Cap,Classic Cap,NaN,35,18–25,Domestic,False,Team Store,2024-04-30 18:57:00,10026081,NaT
3,10000000,20000003,Cap,Classic Cap,NaN,35,<18,Domestic,True,Online,2024-02-01 18:25:00,10005726,2024-02-09 12:35:00
4,10000000,20000004,Cap,Classic Cap,NaN,35,<18,International,False,Team Store,2024-11-24 14:07:00,10042598,NaT

2. Fanbase Engagement

In [16]:
fanbase_engagement_df = pd.read_excel("FirstByte/fanbase_engagement.xlsx")
fanbase_engagement_df.head()

   Membership_ID Age_Group  Games_Attended  Seasonal_Pass Customer_Region
0       10218708     18-25               3          False          Canada
1       10043567     18-25               2          False          Canada
2       14272475     41-60               2          False          Canada
3       10034985     18-25               5          False          Canada
4       10004699     18-25               7          False          Canada

3. Stadium Operations

In [17]:
stadium_operations_df = pd.read_excel("FirstByte/stadium_operations.xlsx")
stadium_operations_df.head()

   Month      Source  Revenue
0      1  Upper Bowl    25020
1      2  Upper Bowl   686664
2      3  Upper Bowl   434112
3      4  Upper Bowl   390879
4      5  Upper Bowl   286524